[package]
name = "astexplorer-syn"
version = "0.1.0"
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
syn = { path = "syn", default-features = false, features = ["parsing", "extra-traits"] }
wasm-bindgen = "0.2.39"

[build-dependencies]
serde = { version = "1.0.89", features = ["derive"] }
indexmap = { version = "1.0.2", features = ["serde-1"] }
serde_json = "1.0.39"

[profile.release]
opt-level = "s"
