[package]
name = "astexplorer-syn"
version = "0.15.29"
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
syn = { version = "=0.15.29", path = "syn", default-features = false, features = ["derive", "parsing", "printing", "full"] }
proc-macro2 = { version = "0.4.27", features = ["span-locations"] }
wasm-bindgen = "0.2.39"

[build-dependencies]
serde = { version = "1.0.89", features = ["derive"] }
indexmap = { version = "1.0.2", features = ["serde-1"] }
serde_json = "1.0.39"
quote = "0.6.11"
proc-macro2 = "0.4.27"

[profile.release]
opt-level = "z"
lto = true
